// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.fucapi.wspoc.domain;

import br.fucapi.wspoc.domain.Pessoa;

privileged aspect Pessoa_Roo_JavaBean {
    
    public String Pessoa.getNome() {
        return this.nome;
    }
    
    public void Pessoa.setNome(String nome) {
        this.nome = nome;
    }
    
    public Long Pessoa.getCpf() {
        return this.cpf;
    }
    
    public void Pessoa.setCpf(Long cpf) {
        this.cpf = cpf;
    }
    
}
