// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.fucapi.wspoc.service;

import br.fucapi.wspoc.domain.Pessoa;
import br.fucapi.wspoc.service.PessoaServico;
import java.util.List;

privileged aspect PessoaServico_Roo_Service {
    
    public abstract long PessoaServico.countAllPessoas();    
    public abstract void PessoaServico.deletePessoa(Pessoa pessoa);    
    public abstract Pessoa PessoaServico.findPessoa(Long id);    
    public abstract List<Pessoa> PessoaServico.findAllPessoas();    
    public abstract List<Pessoa> PessoaServico.findPessoaEntries(int firstResult, int maxResults);    
    public abstract void PessoaServico.savePessoa(Pessoa pessoa);    
    public abstract Pessoa PessoaServico.updatePessoa(Pessoa pessoa);    
}
