// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.fucapi.wspoc.domain;

import br.fucapi.wspoc.domain.Pessoa;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Pessoa_Roo_Json {
    
    public String Pessoa.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public String Pessoa.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(this);
    }
    
    public static Pessoa Pessoa.fromJsonToPessoa(String json) {
        return new JSONDeserializer<Pessoa>().use(null, Pessoa.class).deserialize(json);
    }
    
    public static String Pessoa.toJsonArray(Collection<Pessoa> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static String Pessoa.toJsonArray(Collection<Pessoa> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<Pessoa> Pessoa.fromJsonArrayToPessoas(String json) {
        return new JSONDeserializer<List<Pessoa>>().use(null, ArrayList.class).use("values", Pessoa.class).deserialize(json);
    }
    
}
