// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.fucapi.wspoc.repository;

import br.fucapi.wspoc.domain.Pessoa;
import br.fucapi.wspoc.repository.PessoaRepositorio;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect PessoaRepositorio_Roo_Jpa_Repository {
    
    declare parents: PessoaRepositorio extends JpaRepository<Pessoa, Long>;
    
    declare parents: PessoaRepositorio extends JpaSpecificationExecutor<Pessoa>;
    
    declare @type: PessoaRepositorio: @Repository;
    
}
