// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.fucapi.wspoc.service;

import br.fucapi.wspoc.domain.Pessoa;
import br.fucapi.wspoc.repository.PessoaRepositorio;
import br.fucapi.wspoc.service.PessoaServicoImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PessoaServicoImpl_Roo_Service {
    
    declare @type: PessoaServicoImpl: @Service;
    
    declare @type: PessoaServicoImpl: @Transactional;
    
    @Autowired
    PessoaRepositorio PessoaServicoImpl.pessoaRepositorio;
    
    public long PessoaServicoImpl.countAllPessoas() {
        return pessoaRepositorio.count();
    }
    
    public void PessoaServicoImpl.deletePessoa(Pessoa pessoa) {
        pessoaRepositorio.delete(pessoa);
    }
    
    public Pessoa PessoaServicoImpl.findPessoa(Long id) {
        return pessoaRepositorio.findOne(id);
    }
    
    public List<Pessoa> PessoaServicoImpl.findAllPessoas() {
        return pessoaRepositorio.findAll();
    }
    
    public List<Pessoa> PessoaServicoImpl.findPessoaEntries(int firstResult, int maxResults) {
        return pessoaRepositorio.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void PessoaServicoImpl.savePessoa(Pessoa pessoa) {
        pessoaRepositorio.save(pessoa);
    }
    
    public Pessoa PessoaServicoImpl.updatePessoa(Pessoa pessoa) {
        return pessoaRepositorio.save(pessoa);
    }
    
}
